name: TaxCollector
version: 1.1
author: Wolinski Piotr
main: com.gmail.wolinskip.taxcollector.TaxCollector
depend: [Vault]
permissions:
 taxcollector.immunity:
  description: Gives tax immunity to player
  default: op
 taxcollector.signs.create:
  description: Allows player to create sign with tax counter
  default: op
 taxcollector.signs.refresh:
  description: Allows player to refresh sign data on right click
  default: op